### ISSUE TITLE
Local/automated usage

### ISSUE THREAD

**Issue by jeapostrophe** [NickHeiner/fitbit-export#14]
I'm looking for a way to script this so I can just download everything without going through my browser. Ideally, I'd be able to clone this repo and just run a node-commandline with the required environment variables to get the CSV. How painful would that be for you to support?

**Comment by NickHeiner** [comment]
That would probably be easier overall to develop than the current workflow. It would be much simpler if you could leave a NodeJS process running for several hours (which is how long it would take to get a lot of data, due to Fitbit's API rate limiting) than to just grab as much as you can in the space of a single web request (which often fails to get all data because of rate limiting). 

The authentication could be a bit trickier -- I'm not sure how that works from a command line scenario.

Regardless, that use case is not what this tool is designed to support. If you would like to develop it on your own, and perhaps extract out some common code that both projects could use, then I'd be happy to work with you on that. But for now, this is going to remain a tool for web workflows.

**Comment by jeapostrophe** [comment]
Thanks for the clarification and thoughts about this!
