### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by jibanes** [NickHeiner/fitbit-export#4]
Nick,

I'm trying to setup fitbit-export, I registered a new app on fitbit.com, and I was issued:

* OAuth 2.0 Client ID
* Client (Consumer) Secret
* OAuth 2.0: Authorization URI (set to https://www.fitbit.com/oauth2/authorize)
* OAuth 2.0: Access/Refresh Token Request URI (set to https://api.fitbit.com/oauth2/token)
* Client (Consumer) Key
* OAuth 1.0a: Temporary Credentials (Request Token) URL
* OAuth 1.0a: Token Credentials (Access Token) URL
* OAuth 1.0a: Authorize URL

your application expects the following environment variables, as I understand:
    FITBIT_DATA_EXPORT_CLIENT_KEY
    FITBIT_DATA_EXPORT_CLIENT_SECRET
    FITBIT_DATA_EXPORT_DEV_CLIENT_KEY
    FITBIT_DATA_EXPORT_DEV_CLIENT_SECRET

and presumably
    FITBIT_DATA_EXPORT_SESSION_SECRET
    FITBIT_DATA_EXPORT_DEV_SESSION_SECRET

Could you tell me which value goes where? Also, once I login, through your app, to fitbit.com, I get issued what looks like a hash, but I'm not sure where it ultimately goes.

Finally, when setting up an application on dev.fitbit.com, what should those settings be like:
* OAuth 2.0 Application Type
* Callback URL
* Default Access Type
* Add a subscriber (?)

Thanks!

**Comment by NickHeiner** [comment]
Hi. The different between the normal and the `DEV` values is that they are two different apps registered on Fitbit. In the `DEV` version, the callback url is localhost, so I can develop locally. (The specific value I use is `http://fitbit-export.hexxie.com:3001/auth/fitbit/callback`. `hexxie` is a localhost loopback.) In the non-`DEV` version, the callback url is the production endpoint. For my app, this url starts with with `http://fitbit-export.azurewebsites.net/`. 

* The `*_SESSION_SECRET` vars are any random string you can imagine.
* The `*_CLIENT_KEY` vars are values labelled "Client (Consumer) Key" in the Fitbit console.
* The `*_CLIENT_SECRET` vars are the valued labelled "Client (Consumer) Secret" in the Fitbit console.

* OAuth 2.0 application type should be `server`, since this app does server-side auth.
* For "Default Access Type", you only need Read access. This app does not write anything.
* You do not need to add a subscriber. I think that has to do with receiving notifications.

Does that answer your question?

**Comment by jibanes** [comment]
so the callback url, in the fitbit application settings is:
http://localhost
or
http://localhost:3001
?

**Comment by jibanes** [comment]
works great, thank you.
I have been able to retrieve the data in my browser, does the cookie ever expire? I would like to be able to query this from R (using the same cookie); it would help me in my workouts; initial test shows that it works well, but I don't know if the cookie itself ever expires; or perhaps there's a better way to do this? A script would be ideal.
I really like the csv format, very convenient.

**Comment by NickHeiner** [comment]
What are you trying to do? Why are you trying to run the server locally instead of just using http://fitbit-export.azurewebsites.net/ where it is deployed? 

I'm glad that my clarification helped. 

I'm not quite sure what you're asking. Fitbit will make your authentication expire eventually. Why do you care if your cookie expires? Is downloading the CSV once not good enough?

**Comment by jibanes** [comment]
Hello Nick.

Yes I'm running it as my own service; a perhaps better way to understand how it works.

> Fitbit will make your authentication expire eventually.

okay, I'll measure that.

> Why do you care if your cookie expires?
> Is downloading the CSV once not good enough?

I have meant to download it once a day, so R could email me daily the results from a linear regression and related graphics (after crunching the data); nothing more than playing with the dataset mind you; health data is even more fun than the stock market.

I think I'd rather have it automated as such, but let me know if it's too much trouble; I understand.

Thanks

**Comment by NickHeiner** [comment]
Ok, I still don't understand the benefit of running the service locally. If the Fitbit auth is going to expire after some time anyway, then why don't you just script up a browser to click through the production service and download your results?

The current code does not support heartbeat, but you're welcome to send a PR to add that! :smile:

**Comment by jibanes** [comment]
I'll rewrite your code.
closing ticket, this is going nowhere.

**Comment by NickHeiner** [comment]
Are you trying to be rude? (I'm sorry, but over a text-based medium I'm having a hard time figuring that out.)

**Comment by ramsamdam** [comment]
Hello Nick, i am setting up the code, could you please tell where to enter the following values i am unable to locate them 
FITBIT_DATA_EXPORT_CLIENT_KEY
FITBIT_DATA_EXPORT_CLIENT_SECRET

**Comment by NickHeiner** [comment]
As the docs note, those values need to be environment variables. You should look up how to set environment variables for your operating system.
